[GH-1617] connectivity issues feedback
lambdaclass/champions_of_mirra pull request #1798
Opened 2024-05-29 15:33 UTC by Nico-Sanchez

> [!WARNING]  
> This has to be merged with https://github.com/lambdaclass/mirra_backend/pull/619

Works towards solving #1617 

## Motivation

When a user has connectivity issues, feedback communicating this should be returned to the user.

## Summary of changes

- An algorithm measuring jitter (high variations of ping between messages) and the time elapsed since the last update were implemented.
- When any of these two cases are met, a bad connection icon will be display on the center of the screen.
- For the icon to disappear the connection must be stabilized.
- If the client receives no messages for 10 seconds, then it will return to the main screen with a disconnection message popup.

All the parameters used in the algorithms to detect the stability can be set in the backend file `client_config.json`.

## How has this been tested?

### To test the complete lack of messages

This won't work if you are testing on the Unity editor since to disconnect the computer to the internet or kill the backend running locally you have to loose focus of the application, and by the way Unity handles this the icon will appear, even if no connection issues arise, tainting the results of the test.

- Enter a match and in the middle of it disconnect your device from the backend. You should see the icon popup after 3 seconds without internet, then after 10 seconds the game should take you to the main screen with a popup explaining what happened.

### To test jittering

- You'll have to try this al least once with a good connection to see that the icon doesn't appear.
- After that try to play a match with a bad connection, see that when the match itself feels laggy the icon is displayed, and when the connection is stable again, and you can play correctly, the icon disappears. It's best to pay attention to the bots in the game to see if your connection is good, since your own character has client prediction so it might move correctly even with a bad connection.

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-05-30 22:17 UTC, manucamejo requested changes

2024-05-30 22:17 UTC, manucamejo commented on client/Assets/Scripts/ConnectionHealthAnalyzer.cs
> +                unstableConnection = false;
You are calculating the same things several times: `timestampDifferences.Max()`
I also think that we should separate the algorithm to activate and deactivate the icon because they are things that we should check with different time intervals.

2024-05-30 22:19 UTC, Nico-Sanchez commented on client/Assets/Scripts/ConnectionHealthAnalyzer.cs
> +        GameServerConnectionManager.Instance.currentPing = (uint)timestampDifferences.Last();
We don't really need to do that. It was for testing purposes. See that it's changing the currentPing and it shouldn't.
I deleted it in [Restore ping shown in UI](https://github.com/lambdaclass/champions_of_mirra/pull/1798/commits/be7ab2e0eb1268cb3d89e8aebe584f72aec3dcea)
Seems like it got pushed again in future commits. Will delete it again.

2024-05-30 22:22 UTC, Nico-Sanchez commented on client/Assets/Scripts/ConnectionHealthAnalyzer.cs
> +                unstableConnection = false;
Done the first one.
About the 2nd one, we can totally do that. However, I'd like to know the motivation behind that change since its working fine now.
I believe you mentioned something about performance in our huddle. Do we have any tool to measure the algorithm performance?

2024-05-31 21:15 UTC, tkz00 commented on client/Assets/Scripts/ConnectionHealthAnalyzer.cs
> +                unstableConnection = false;
We discussed this in person with Nico and Manu, different methods for detecting spikes in latency vs checking if the connection is stable have been implemented to encapsulate behavior that previously was inside OnGameEventTimestampChanged, but it was agreed that a reduced frequency to check if the connection is stable, and by extension, the disappearance of the icon, would be left for a future iteration of the feature.

2024-05-31 21:55 UTC, alfopisano approved these changes
Nice!! Tested as described on an iOS build and it worked as expected 🙌

2024-06-03 15:58 UTC, alfopisano submitted a review, later dismissed
Tested again on iOS build and everything worked fine!!

2024-06-03 19:48 UTC, manucamejo requested changes

2024-06-03 19:48 UTC, manucamejo commented on client/Assets/Scripts/ConnectionHealthAnalyzer.cs
> +            long msSinceLastUpdate = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() - lastUpdateTimestamp;
You should move this variable to the top of the file, we are creating a new variable in each update.

2024-06-03 19:48 UTC, manucamejo commented on client/Assets/Scripts/ConnectionHealthAnalyzer.cs
> +        else if(IsConnectionStable(timestampDifferences))
This functionality should run every second instead of on each update. But don't change it now. Can you create an issue for that?

2024-06-03 20:40 UTC, manucamejo approved these changes

2024-06-03 20:57 UTC, alfopisano approved these changes

2024-06-03 20:57 UTC, merged