Authentication with JWT
lambdaclass/champions_of_mirra pull request #1803
Opened 2024-05-31 18:47 UTC by AminArria

## Motivation

Explain why not how.

## Summary of changes

- [x] Add logic for guest sign in
- [x] Send JWT when connecting to websockets
- [ ] Refresh JWT 

## How has this been tested?

Test together with https://github.com/lambdaclass/mirra_backend/pull/665 by playing games and seeing the match results stored

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-06-10 14:36 UTC, ncontinanza requested changes

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/GameServerConnectionManager.cs
> +        string gateway_jwt = PlayerPrefs.GetString("gateway_jwt");
Let's change `gateway_jwt` to `gatewayJwt` here and in all the other appeareances

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/GuestSignIn/GuestSignInController.cs
> +    }
```suggestion
```

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/GuestSignIn/GuestSignInController.cs
> +        Action<string> successCallback = raw_response => {
Same here, `rawResponse` instead of `raw_response`

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +                raw_response => {
`rawResponse`

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        string gateway_jwt = PlayerPrefs.GetString("gateway_jwt");
`gatewayJwt`

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        public string client_id;
`ClientId`

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        public string client_id;
`ClientId`

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        public string gateway_jwt;
`GatewayJwt`

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        public string user_id;
`UserId`

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        public string gateway_jwt;
`GatewayJwt`

2024-06-10 14:36 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +    public static IEnumerator CreateGuestUser(
I'm getting an error here when trying to enter as guest:

```
HTTP/1.1 404 Not Found
UnityEngine.Debug:Log (object)
GuestSignInController/<>c:<SignIn>b__5_1 (string) (at Assets/Scripts/GuestSignIn/GuestSignInController.cs:53)
ServerUtils/<CreateGuestUser>d__9:MoveNext () (at Assets/Scripts/Utils/ServerUtils.cs:295)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)
```

2024-06-10 16:10 UTC, AminArria commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +    public static IEnumerator CreateGuestUser(
Are you sure your backend and client where in the latest version? I can't replicate this particular error and the 404 seems weird

Also, the log from the server would be usefull

2024-06-10 16:23 UTC, AminArria commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        public string client_id;
Do you know how to make the field `ClientId` but the json serialization `client_id` cause I can't find a simple way to do it and otherwise I need to keep `client_id` as that is the expected JSON case

2024-06-11 14:37 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +        public string client_id;
I searched a bit about how to configure this but couldn't find much, let's leave it like this. I'll mark all these comments as solved.

2024-06-11 14:38 UTC, ncontinanza commented on client/Assets/Scripts/Utils/ServerUtils.cs
> +    public static IEnumerator CreateGuestUser(
I tried to reproduce it, but there are some new errors in the client that prevent it from compiling :(

2024-06-11 17:14 UTC, AminArria commented on client/Assets/Scripts/GameServerConnectionManager.cs
> +        string gateway_jwt = PlayerPrefs.GetString("gateway_jwt");
Fixed this and all the case issues https://github.com/lambdaclass/champions_of_mirra/pull/1803/commits/05ce6840a1e959839ac1f854c4745c2f0905f7ba

2024-06-11 19:53 UTC, ncontinanza approved these changes

2024-06-13 22:01 UTC, agustinesco approved these changes
LGTM!

2024-06-13 22:01 UTC, merged