Add google sign-in docs
lambdaclass/champions_of_mirra pull request #1853
Opened 2024-06-18 16:39 UTC by Nico-Sanchez

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-06-18 21:51 UTC, AngieDutra requested changes
Awesome. Just a few comments.
Disclaimer: I didn't test the whole doc, just the player settings part

2024-06-18 21:51 UTC, AngieDutra commented on docs/src/google_sign_in.md
> +### Other Settings tab
I would specify this is a tab in 'Player' section

2024-06-18 21:51 UTC, AngieDutra commented on docs/src/google_sign_in.md
> +- Scripting backend: IL2CPP.
I would clarify this is in the Android tab since in IOS tab this option is disabled

2024-06-19 14:17 UTC, Nico-Sanchez commented on docs/src/google_sign_in.md
> +### Other Settings tab
Done!

2024-06-19 14:20 UTC, Nico-Sanchez commented on docs/src/google_sign_in.md
> +- Scripting backend: IL2CPP.
Nice catch! Done!

2024-06-19 19:54 UTC, AngieDutra approved these changes
Awesome and also reviewed the IOS process

2024-06-20 18:19 UTC, alfopisano approved these changes

2024-06-20 18:19 UTC, merged