[VFX] Added Giant Fruit item effect (#1822)
lambdaclass/champions_of_mirra pull request #1868
Opened 2024-06-26 20:42 UTC by AngieDutra

## Motivation

Our giant fruit item was missing it's effect

## Summary of changes

This PR adds that

## How has this been tested?

Try it out in the items scene since it still needs to be adapted to the game

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-06-27 21:15 UTC, AngieDutra commented
I'll fix multiple player giant fruit effect since now you can only see the scaling animation for the client

2024-07-02 17:41 UTC, tkz00 requested changes
When other players become small after the fruit's effect has worn out, they get the yellow glow, but not for my own character.

https://github.com/lambdaclass/champions_of_mirra/assets/67983386/08e33eea-ee07-4ef5-9fd7-6918d174eaad

2024-07-02 17:43 UTC, alfopisano commented
On the opposite side, I did not experience that Issue playing on my iOS:
https://github.com/lambdaclass/champions_of_mirra/assets/116388676/e465dcda-ff68-4957-9aae-82f7bf341859

2024-07-05 20:23 UTC, tkz00 requested changes

2024-07-05 20:23 UTC, tkz00 commented on client/Assets/Scripts/Effects/EffectCharacterMaterialController.cs
> +        /// FOR TEST POPOUSES ONLY, DO NOT SHIP
Should this lines be removed?

2024-07-05 20:36 UTC, tkz00 submitted a review, later dismissed
Great work! Looks amazing, tested on my android!

2024-07-05 20:40 UTC, AngieDutra commented on client/Assets/Scripts/Effects/EffectCharacterMaterialController.cs
> +        /// FOR TEST POPOUSES ONLY, DO NOT SHIP
Yes, forgot to delete the comment and the print, I'll do it!

2024-07-05 21:56 UTC, tkz00 approved these changes
Great! Works on my android!

2024-07-05 23:30 UTC, tvillegas98 approved these changes

2024-07-05 23:30 UTC, merged