Add bounty pick time to zone shrink time
lambdaclass/champions_of_mirra pull request #1873
Opened 2024-06-27 21:53 UTC by alfopisano

## Motivation
When the bounties PR got merged we did not notice a bug on the zone shrink timer. This was due to the extra time added at the beginning of the battle to let you choose a bounty. We need to also add this amount of time to the zone shrink one. 

## Summary of changes
Added the bounty pick time gave by the backend to the zone shrink one.

## How has this been tested?
You need to **play a normal match** not a quick game because there the zone is inactive. Play and take a look at the zone timer and check if it is working properly. 

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-06-28 17:46 UTC, AngieDutra submitted a review, later dismissed
Good fix. This is a temporary fix. @Nico-Sanchez will create an issue for this in back repo
Tested in desktop and Android device and works good in both

2024-07-01 18:52 UTC, tkz00 requested changes
Te counter seems to be 5 seconds higher than it should be, in all the phases except for the first one.

https://github.com/lambdaclass/champions_of_mirra/assets/67983386/f8af1d7d-e0c7-4556-8545-72b07bea7853

2024-07-02 18:17 UTC, AngieDutra submitted a review, later dismissed
Tested in Android and desktop. It's working as expected IMO

2024-07-03 17:26 UTC, tkz00 approved these changes
Great! Works amazingly on my android!

2024-07-04 19:15 UTC, AngieDutra commented on client/Assets/Scripts/GameServerConnectionManager.cs
> +                    var position = gameState.Players[this.playerId].Position;
Question, why not `Position position = gameState.Players[this.playerId].Position;`? instead of using `var`?

2024-07-04 19:20 UTC, alfopisano commented on client/Assets/Scripts/GameServerConnectionManager.cs
> +                    var position = gameState.Players[this.playerId].Position;
This was something that already was on the script when I first opened the PR. I am now checking main and that variable has been deleted so I will delete it also.

2024-07-04 19:55 UTC, manucamejo approved these changes

2024-07-04 20:39 UTC, tvillegas98 approved these changes
LGTM!

2024-07-04 20:39 UTC, merged