Add missing bounty information
lambdaclass/champions_of_mirra pull request #1877
Opened 2024-06-28 23:46 UTC by agustinesco

>[!Warning]
> This pr should be merged alongside this backend pr

## Motivation

The bounty feature was missing some functionalities and they were implemented in the backend so this pr updates the proto messages

2024-07-10 19:54 UTC, jazimp commented
visual approval ✅

2024-07-10 21:10 UTC, tkz00 requested changes
https://github.com/lambdaclass/champions_of_mirra/assets/67983386/c644cdf3-a887-4218-b283-dbc36f9c4e16

When selecting the "Receive less than 200 damage" bounty, it is automatically completed, when it should be completed at the end of the match. I would tend to guess this is more of a backend problem, since the client should only display what is receives from there, but I could be wrong.

2024-07-10 21:16 UTC, tkz00 requested changes
https://github.com/lambdaclass/champions_of_mirra/assets/67983386/cf62bc6e-542f-4fcf-916f-b88bdd134ed5

Also I feel it would be better for the actual currency to start on the previous value and then, when the animation happens to change with another animation, not to start with the claimed prize already added (in the video 40).

2024-07-11 13:47 UTC, alfopisano commented
> Screen.Recording.2024-07-10.at.5.51.22.PM.mov 
> When selecting the "Receive less than 200 damage" bounty, it is automatically completed, when it should be completed at the end of the match. I would tend to guess this is more of a backend problem, since the client should only display what is receives from there, but I could be wrong.

Yes, this is a backend problem. Actually that bounty is being replaced because of that issue and because the bounty UI design does not contemplate descriptions that long.

2024-07-11 18:19 UTC, tkz00 requested changes
Also could we rename `quick game button (1).png` to something else? Well, in general we should try to keep some kind of naming convention for all files.

After these correction I believe it would be a good idea to do a playtest with one or two other people to check this behaves as expected in a real game situation, instead of with bots.

2024-07-11 18:19 UTC, tkz00 commented on client/Assets/Scripts/Battle.cs
> +        if (playerUpdate.Player.BountyCompleted && !bountyCompleted) {
This logic should be moved inside the `if` block on line 635, since each player only needs to check if himself has completed the bounty. Right now if any player has completed the bounty the popup appears.


https://github.com/lambdaclass/champions_of_mirra/assets/67983386/a3fa65e5-2a51-4e54-803b-1a0c1162a951

2024-07-12 15:53 UTC, AngieDutra commented on client/Assets/Scripts/UI/BountyCompletionManager.cs
> +    IEnumerator BountyCompletionPopUpAnimation()
Are you using a Corotine just for animation pourpuses?

2024-07-12 15:53 UTC, AngieDutra commented on client/Assets/Scenes/Battle.unity
What are the changes done in this scene?

2024-07-12 15:53 UTC, AngieDutra commented on client/Assets/Scenes/MainScreen.unity
What are the changes done in this scene?

2024-07-12 16:03 UTC, AngieDutra commented
Also, I get this modified meta
<img width="450" alt="Screenshot 2024-07-12 at 13 02 24" src="https://github.com/user-attachments/assets/b9f22d45-ee4a-4611-83d3-ced89decef0f">

2024-07-12 16:06 UTC, alfopisano commented on client/Assets/Scripts/UI/BountyCompletionManager.cs
> +    IEnumerator BountyCompletionPopUpAnimation()
Yes, do you have a better suggestion?

2024-07-12 16:07 UTC, alfopisano commented on client/Assets/Scenes/Battle.unity
This changes were made because I need to assign variables that are outside of the prefab.

2024-07-12 16:08 UTC, alfopisano commented on client/Assets/Scenes/MainScreen.unity
Because I reverted a change that was made outside of the prefab to have the scene as in the prefab is.

2024-07-12 16:09 UTC, alfopisano commented on client/Assets/Scripts/UI/BountyCompletionManager.cs
> +    IEnumerator BountyCompletionPopUpAnimation()
I am using it because I need to wait a specific amount of time.

2024-07-12 17:33 UTC, AngieDutra commented on client/Assets/Scripts/UI/BountyCompletionManager.cs
> +    IEnumerator BountyCompletionPopUpAnimation()
I think you can use AppendInterval(float interval) for that and avoid using a coroutine for that. But let's talk about this

2024-07-12 17:33 UTC, AngieDutra commented on client/Assets/Scripts/UI/BountyCompletionManager.cs
> +        Destroy(popUp);
I would do this a void, use append interval for what you need and change the destroy to `Destroy(popUp, 1f);`

2024-07-12 19:28 UTC, AngieDutra commented on client/Assets/Scripts/UI/MainScreenManager.cs
> +    IEnumerator BountyRewardAnimation(int totalGold)
Sme here. Use appenDinterval instead a coroutine

2024-07-12 20:11 UTC, alfopisano commented on client/Assets/Scripts/UI/BountyCompletionManager.cs
> +        Destroy(popUp);
Great!! Did those suggestions ✨

2024-07-12 21:33 UTC, alfopisano commented on client/Assets/Scripts/UI/MainScreenManager.cs
> +    IEnumerator BountyRewardAnimation(int totalGold)
Done!!

2024-07-15 15:34 UTC, AngieDutra reviewed
I see a position difference between the implementation and the reference. Other that that I see everything else fixed and working as expected!

Implementation:
<img width="1708" alt="Screenshot 2024-07-15 at 10 27 47" src="https://github.com/user-attachments/assets/79f06fde-ef2d-4b03-9992-18f20c320dd9">

Reference:
<img width="823" alt="Screenshot 2024-07-15 at 11 12 46" src="https://github.com/user-attachments/assets/cbc4ded6-ad4c-4257-914b-e494caba2c0e">

Here is what I did to make it look like the reference
<img width="1698" alt="Screenshot 2024-07-15 at 12 32 28" src="https://github.com/user-attachments/assets/0761d7d4-e324-407a-a692-de92b90a4867">

2024-07-15 15:41 UTC, AngieDutra approved these changes
Tested in desktop and mobile device. Everything is working as expected

2024-07-15 17:10 UTC, AngieDutra commented
I think the animation in Main Screen could be a lot better. I did an issue for this to iterate
Issue #1937

2024-07-16 14:36 UTC, merged