Fix effects handling
lambdaclass/champions_of_mirra pull request #1910
Opened 2024-07-06 16:45 UTC by tvillegas98

## Motivation

Magic boots trail effect wasn't being deleted

## Summary of changes

This PR fixes that. Now you should be able to apply multiple effects or just use one, in this case the magic boots, and have them deleted when they should

## How has this been tested?

Start a match and test multiple uses of effects and just using the boots

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-07-06 19:26 UTC, saugon approved these changes
Tested on iphone 👍🏻

2024-07-08 15:47 UTC, tkz00 requested changes

2024-07-08 15:47 UTC, tkz00 commented on client/Assets/Scripts/Effects/CharacterMaterialManager.cs
> +    public void applyEffectByKey(MaterialSettingsKey key)
```suggestion
    public void ApplyEffectByKey(MaterialSettingsKey key)
```

2024-07-08 15:47 UTC, tkz00 commented on client/Assets/Scripts/Effects/CharacterMaterialManager.cs
> +            block.applyToMaterial(renderer.sharedMaterial);
Maybe also change this to ApplyToMaterial, but since that modifies a new file it could be confusing, I leave it to you

2024-07-08 15:47 UTC, tkz00 commented on client/Assets/Scripts/Effects/EffectCharacterMaterialController.cs
> +        character_material_manager?.applyEffectByKey(material_settings_key);
```suggestion
        character_material_manager?.ApplyEffectByKey(material_settings_key);
```

2024-07-08 15:47 UTC, tkz00 commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +        CharacterFeedbacks characterFeedbacks = character.GetComponent<CharacterFeedbacks>(); // maybe cache this? We can optimize this later.
What do you think about adding a conditional to check if `playerUpdate.Player.Effects.Count > 0` before retrieving CharacterFeedbacks?

2024-07-08 16:02 UTC, AngieDutra commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +        CharacterFeedbacks characterFeedbacks = character.GetComponent<CharacterFeedbacks>(); // maybe cache this? We can optimize this later.
Then it won't reset the last vfx once it reaches to 0 the effects

2024-07-08 16:04 UTC, AngieDutra commented on client/Assets/Scripts/Effects/CharacterMaterialManager.cs
> +    public void applyEffectByKey(MaterialSettingsKey key)
done

2024-07-08 16:07 UTC, tkz00 commented on client/Assets/Scripts/CharacterFeedbackManager.cs
> +        CharacterFeedbacks characterFeedbacks = character.GetComponent<CharacterFeedbacks>(); // maybe cache this? We can optimize this later.
Oh yeah! You're right!

2024-07-08 19:37 UTC, tkz00 approved these changes
Works great on my android!

2024-07-08 20:18 UTC, saugon approved these changes

2024-07-08 21:38 UTC, tkz00 approved these changes
Works great on my android!

2024-07-08 21:39 UTC, merged