[GH-1367] Fix dotween warnings
lambdaclass/champions_of_mirra pull request #1938
Opened 2024-07-15 19:54 UTC by AngieDutra

Closes #1367 

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-07-16 19:59 UTC, tkz00 requested changes
<img width="299" alt="Screenshot 2024-07-16 at 4 49 19 PM" src="https://github.com/user-attachments/assets/c2b972dd-0c16-48dc-93ea-58f9ac65b4ca">

I get a lot of DOTween warnings when on the battle scene.

Also I wanted to ask if you had any insight on what tweens don't stop when changing scenes, where this ones causing some of the warnings? Was this why you had to add a script to kill all the tweens when changing scenes? Seems like pretty bad design from DOTween's part.

2024-07-16 19:59 UTC, tkz00 commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +    CanvasGroup logoImage, buttonsCanvas, singOutContainer, singInContainer;
```suggestion
    CanvasGroup logoImage, buttonsCanvas, singOutContainer, signInContainer;
```

Since where at it.

2024-07-17 22:46 UTC, AngieDutra commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +    CanvasGroup logoImage, buttonsCanvas, singOutContainer, singInContainer;
Done!

2024-07-18 18:00 UTC, tkz00 requested changes
<img width="311" alt="Screenshot 2024-07-18 at 2 51 32 PM" src="https://github.com/user-attachments/assets/3612917b-5ded-46be-8624-3cdf95475096">

I got this DOTween warning that wasn't contemplated on the description of the PR, I didn't get what action triggered this, but at least it specifies which script caused it.

2024-07-18 18:11 UTC, tkz00 commented on client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
What are these changes? It has to do with the responsiveness of an element on the main screen?

2024-07-18 18:23 UTC, tkz00 commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +        Sequence titleDisplaySequence = DOTween.Sequence();
This animation differs from the current one in main, I don't know if this was intentional or not, let me know!

https://github.com/user-attachments/assets/fbeb390b-174d-43ba-8085-f4561e780167


https://github.com/user-attachments/assets/1905091a-716a-4992-ad14-2ee7741f2a26

2024-07-18 18:30 UTC, tkz00 commented on client/Assets/Scripts/DamagePopUpAnimation.cs
> +        popUpRectTransform = GetComponent<RectTransform>();
I believe this `GetComponent` call should be replaced by referencing the component in the prefab.

2024-07-18 18:36 UTC, tkz00 commented on client/Assets/Scripts/DamagePopUpAnimation.cs
> +        if (GetComponent<RectTransform>())
```suggestion
        if (popUpRectTransform != null)
```

2024-07-18 19:36 UTC, tkz00 commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +    CanvasGroup logoImage, buttonsCanvas, singOutContainer, signInContainer;
```suggestion
    CanvasGroup logoImage, buttonsCanvas, signOutContainer, signInContainer;
```

2024-07-19 21:05 UTC, AngieDutra commented on client/Assets/Scripts/UI/TitleScreenController.cs
> +        Sequence titleDisplaySequence = DOTween.Sequence();
You are right. I'll make it more similar to the one in main

2024-07-19 21:09 UTC, AngieDutra commented on client/Assets/Scripts/DamagePopUpAnimation.cs
> +        if (GetComponent<RectTransform>())
Actually, I dont need this check. It was a debugging process for the warnings I forgot to delete

2024-07-19 21:16 UTC, AngieDutra commented on client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
I was doing fixing a UX issue regarding the press animation for buttons but since the last merge to main I no longer need this

2024-07-22 14:35 UTC, tkz00 approved these changes
Great! Tested on my android!

2024-07-22 19:20 UTC, ncontinanza approved these changes
LGTM!

2024-07-22 19:20 UTC, merged