[GH-1876] Add missing bounty information
lambdaclass/champions_of_mirra pull request #1941
Opened 2024-07-16 16:00 UTC by tvillegas98

>[!Warning]
> This pr should be merged alongside [this backend pr](https://github.com/lambdaclass/mirra_backend/pull/733)

>[!Warning]
> The original PR was merged and then reverted (https://github.com/lambdaclass/champions_of_mirra/pull/1877), this is the new PR for merging this branch.

Closes #1876

## Motivation
The bounty feature was missing some functionalities and they were implemented in the backend so this pr updates the proto messages.

We needed to the following to the client: 
- Pop up in-game when bounty is completed. 
- Add functionality to the 'claim' button on the deathsplash when bounty is completed. 
- Hide bounties container on deathsplash when player does not complete it. 
- Add animation of the reward when returning to main screen after completing the selected bounty.

Result: 
New main screen design:
<img width="903" alt="Screenshot 2024-07-10 at 16 27 46" src="https://github.com/lambdaclass/champions_of_mirra/assets/116388676/2dc54e2a-2d96-4091-b7c9-e8bf6c90f8a8">

Pop up in-game
<video src="https://github.com/lambdaclass/champions_of_mirra/assets/116388676/f83f6ccf-8f97-426f-ac80-392ea00aba04">

Deathsplash when bounty completed, claim button animation and reward animation when returning to main screen after completing the bounty:
<video src="https://github.com/lambdaclass/champions_of_mirra/assets/116388676/a9270544-c1ef-479a-a077-d61b2f719d07">

Deathsplash when bounty not completed
<img width="901" alt="Screenshot 2024-07-05 at 18 05 10" src="https://github.com/lambdaclass/champions_of_mirra/assets/116388676/4fcffd0a-c29a-44b1-8bae-a145d03f6b86">

## How has this been tested?
Start a battle and select a bounty, check the following works correctly:
- When completing it the pop-up is shown on the screen
- When completing it you should see the bounty information on the deathsplash, check that the claim button works and gets disabled after claiming
- When returning to main screen after completing a bounty an animation with the bounty reward should come from the play button to the gold container. Check also that the gold amount is being updated correctly
- If the bounty is not completed you should see nothing related to it on the deathsplash

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-07-16 16:09 UTC, tkz00 approved these changes
Works great, tested on my android.

2024-07-16 19:51 UTC, agustinesco requested changes
The pr seems to be working as expected! Let's just fix the issue where the bounty overlaps the options buttons and we should be good to go!
![image](https://github.com/user-attachments/assets/d79e35ff-6d95-4020-a839-61a134675f09)

Also i've left some minor comment's in the code but nothing mandatory

2024-07-16 19:51 UTC, agustinesco commented on client/Assets/Scripts/UI/EndGame/EndGameManager.cs
> +        ColorUtility.TryParseHtmlString("#666666", out disabledButtonColor);
let's be careful with this magic numbers

2024-07-16 19:51 UTC, agustinesco commented on client/Assets/Scripts/UI/EndGame/EndGameManager.cs
> +    GameObject defeatedByContainer,
I'm not a big fan of this way of variable declaration, the only thing we achieve is save up some lines over readability

2024-07-17 21:14 UTC, tkz00 requested changes
https://github.com/user-attachments/assets/161346d2-2e18-4ee4-b8da-596ee16d4af7

When entering the main screen from anywhere besides the battle scene you have 0 coins, either by changing server or closing and reopening the app, even when going to the character list and selecting a new character.

2024-07-17 22:14 UTC, AngieDutra commented on client/Assets/Scripts/UI/EndGame/EndGameManager.cs
> +        ColorUtility.TryParseHtmlString("#666666", out disabledButtonColor);
I think that is a color heex value for a button. I agree it could be a variable tho

2024-07-18 14:05 UTC, tkz00 requested changes
https://github.com/user-attachments/assets/44bf00d7-38da-4046-9958-f8c4f4a1ba6f

When I go to mainscreen from anywhere I get this small delay of a 0 value in the currency counter, this video was recorded using an ngrok, but maybe using the real servers the problem could be worse.

2024-07-18 21:57 UTC, agustinesco approved these changes
LGTM! playtest it in an android build and it worked as a charm!

2024-07-18 22:02 UTC, tkz00 approved these changes
Great! Worked fine on my android!

2024-07-19 14:18 UTC, merged