Add leaderboard scene
lambdaclass/champions_of_mirra pull request #1944
Opened 2024-07-16 21:32 UTC by tkz00

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-07-30 14:20 UTC, AngieDutra commented
Here are some screens for a visual review @jazimp 

<img width="895" alt="Screenshot 2024-07-30 at 11 07 52" src="https://github.com/user-attachments/assets/6d4600e3-276e-4917-b404-ad29dab7906d">
<img width="1722" alt="Screenshot 2024-07-30 at 11 19 28" src="https://github.com/user-attachments/assets/db2ef93f-9e18-48af-905d-a63981d72630">

2024-07-30 14:34 UTC, jazimp commented
I see that the rank and prestige numbers ended up higher. It's not a serious problem and I think it can be adjusted in a future iteration, wdyt @tkz00 @AngieDutra? 
<img width="1609" alt="Captura de pantalla 2024-07-30 a la(s) 11 32 57" src="https://github.com/user-attachments/assets/d5109bf2-57b1-4cb3-9151-d0f17abbf639">

2024-07-30 15:34 UTC, AngieDutra requested changes
General notes:
- When we name assets we use S_ for sprites and TX_ for textures
- Double check the assets are cap at the correct max size

2024-07-30 15:34 UTC, AngieDutra commented on client/Assets/Scripts/Leaderboard/LeaderboardRow.cs
I would to the following:
```
public void SetPlayer(int rank, LeaderboardManager.User user, bool isClientPlayer)
    {
        if (rank != -1)
        {
            rankText.text = rank.ToString();
            if (rank <= 3)
            {
                rankText.fontSize = 50;
                rankBackground.enabled = true;
            }
            switch (rank)
            {
                case 1:
                    rankBackground.sprite = rankOneSprite;
                    break;
                case 2:
                    rankBackground.sprite = rankTwoSprite;
                    break;
                case 3:
                    rankBackground.sprite = rankThreeSprite;
                    break;
            }
        }

        playerName.text = user.username;
        prestigeNumber.text = user.prestige.ToString();

        if (isClientPlayer)
        {
            background.sprite = currentPlayerBackground;
            background.enabled = true;
        }
        else if (rank % 2 == 0)
        {
            background.enabled = true;
        }
    }

```
It's clearer to read and you avoid going through the ranking logic if you don't need to

2024-07-30 15:34 UTC, AngieDutra commented on client/Assets/Prefabs/Camera/LeaderboardScreenCameraUI.prefab
IMO this name change is better to understand
<img width="790" alt="Screenshot 2024-07-30 at 12 26 21" src="https://github.com/user-attachments/assets/031ec7f1-1ebb-48d0-a062-2daf2ff1b249">

2024-07-30 15:35 UTC, AngieDutra commented on client/Assets/Prefabs/Camera/LeaderboardScreenCameraUI.prefab
Also check overrides:
<img width="921" alt="Screenshot 2024-07-30 at 12 34 47" src="https://github.com/user-attachments/assets/9553afea-4f1a-4f88-bf8c-7142221e210d">
<img width="344" alt="Screenshot 2024-07-30 at 12 35 10" src="https://github.com/user-attachments/assets/edd22a87-58ad-484c-8198-cb9530fbf070">

2024-07-31 15:31 UTC, tkz00 commented
> General notes:
> 
>     * When we name assets we use S_ for sprites and TX_ for textures
> 
>     * Double check the assets are cap at the correct max size

Done with both things!

2024-07-31 15:31 UTC, tkz00 commented on client/Assets/Scripts/LoadingSpinner.cs
I've changed `LoadingSpinner` to `LoadingOverlay` it is a much better name.

2024-07-31 15:32 UTC, tkz00 commented on client/Assets/Scripts/Leaderboard/LeaderboardManager.cs
> +                    for(int i = 0; i < response.users.Count; i++)
You're right, it's clearer to read, fixed.

2024-07-31 15:32 UTC, tkz00 commented on client/Assets/Scripts/Leaderboard/LeaderboardManager.cs
> +    LeaderboardRow currentPlayerRow;
Renamed

2024-07-31 15:32 UTC, tkz00 commented on client/Assets/Scripts/Leaderboard/LeaderboardManager.cs
> +                    bool foundCurrentUser = false;
Renamed

2024-07-31 15:32 UTC, tkz00 commented on client/Assets/Scripts/Leaderboard/LeaderboardManager.cs
> +                    if(!foundCurrentUser)
Renamed

2024-07-31 15:32 UTC, tkz00 commented on client/Assets/Scripts/Leaderboard/LeaderboardRow.cs
> +    public void SetPlayer(int rank, LeaderboardManager.User user, bool isCurrentPlayer)
Renamed

2024-07-31 15:33 UTC, tkz00 commented on client/Assets/Scripts/Leaderboard/LeaderboardRow.cs
> +    Sprite currentPlayerBackground;
Renamed

2024-07-31 15:33 UTC, tkz00 commented on client/Assets/Scripts/Leaderboard/LeaderboardRow.cs
> +            background.sprite = currentPlayerBackground;
Renamed

2024-07-31 15:35 UTC, tkz00 commented on client/Assets/Scripts/Leaderboard/LeaderboardRow.cs
> +                rankText.fontSize = 50;
The element in the prefab has a smaller font size, only in the case of rank 1, 2 or 3 is the font going to be set to `50`, I've made a little change related to the next comment where I add a utility method to avoid repeating code.

2024-07-31 15:35 UTC, tkz00 commented on client/Assets/Scripts/Leaderboard/LeaderboardRow.cs
Changed

2024-07-31 15:35 UTC, tkz00 commented on client/Assets/Prefabs/Camera/LeaderboardScreenCameraUI.prefab
Made both changes!

2024-07-31 15:40 UTC, tkz00 commented
I've added updated in game references in the description of the PR

2024-08-01 14:16 UTC, AngieDutra approved these changes
Awesome! All previous bugs were addressed and changes requested were done 
Nice one fixing this previous bug, works like a charm
<img width="1728" alt="Screenshot 2024-08-01 at 11 01 26" src="https://github.com/user-attachments/assets/02310e6f-0b2f-4c34-bcc1-9ac3a3eed157">
<img width="1728" alt="Screenshot 2024-08-01 at 11 00 49" src="https://github.com/user-attachments/assets/6714a6fd-788d-44fd-8f96-5b395b57bc08">
Tested on Android and Unity desktop

2024-08-01 19:24 UTC, tvillegas98 approved these changes
Great work! tested on android

2024-08-01 19:24 UTC, merged