Add sat fix for invalid axis
lambdaclass/champions_of_mirra pull request #1953
Opened 2024-07-19 00:26 UTC by agustinesco

> [!Warning]
> Merge alongside [This backend pr](https://github.com/lambdaclass/mirra_backend/pull/770)

## Motivation

We need that the collision detection an resolution algorithm is the same as the one in the backend, we were missin a fix that avoid players going inside another obstacle and outside of the map when resolving the collision

## Summary of changes

- Added Jeffrey thompson collision detection algorithm
- Added invalid_axis check to SAT algorithm

2024-07-19 19:55 UTC, Nico-Sanchez requested changes
I believe this PR was rushed. I didn't fully reviewed it because I saw a lot of things to fix at first sight.

Please review your own code before leaving it for review.

2024-07-19 19:55 UTC, Nico-Sanchez commented on client/Assets/Scripts/CollisionDetection.cs
> +                result.Add(obstacleGameEntity.id);
All these if's are unnecessary.
I believe it's better to use a switch here, then inside every case, just call the proper function instead of another if, that if could be inside each function and add the entity to the list or not.

2024-07-19 19:55 UTC, Nico-Sanchez commented on client/Assets/Scripts/CollisionDetection.cs
> +    };
What's inside_1 and inside_2? Please avoid this kind of naming, name the variables after what they represent.

2024-07-19 19:55 UTC, Nico-Sanchez commented on client/Assets/Scripts/CollisionDetection.cs
> +        / Math.Pow(line_length, 2);
Is this a dot product? don't call it dot please, that's a different thing.
Don't call it dotProduct either. As I said before, name the variables after what they represent.

2024-07-19 19:55 UTC, Nico-Sanchez commented on client/Assets/Scripts/CollisionDetection.cs
> +    return uA >= 0.0f || uA <= 1.0f &&  uB >= 0.0f || uB <= 1.0f;
This is unreadable. Split the operations and put them in variables named after what they represent, in order to follow the full math operation.
Also uA and uB doesn't tell anything.

2024-07-19 19:55 UTC, Nico-Sanchez commented on client/Assets/Scripts/CollisionDetection.cs
> +    Position otherLineSecondVertex = other_line.vertices[1];
We don't use snake case in C#

2024-07-22 13:36 UTC, agustinesco commented
> I believe this PR was rushed. I didn't fully reviewed it because I saw a lot of things to fix at first sight.
> 
> Please review your own code before leaving it for review.

Sorry! i meant to leave this pr as a draft, i'm still developing it and i didn't want it to just leave it in my computer so i created a pr

2024-07-22 20:57 UTC, agustinesco commented on client/Assets/Scripts/CollisionDetection.cs
> +        / Math.Pow(line_length, 2);
This is in fact dot product, or at least that's what the author of this algorithm says: 

```
 // get dot product of the line and circle
  float dot = ( ((cx-x1)*(x2-x1)) + ((cy-y1)*(y2-y1)) ) / pow(len,2);
```

2024-07-22 21:01 UTC, agustinesco commented on client/Assets/Scripts/CollisionDetection.cs
> +    };
done!

2024-07-22 21:07 UTC, agustinesco commented on client/Assets/Scripts/CollisionDetection.cs
> +    return uA >= 0.0f || uA <= 1.0f &&  uB >= 0.0f || uB <= 1.0f;
This is what the original post of line/line collision detection have:
```
  // calculate the distance to intersection point
  float uA = ((x4-x3)*(y1-y3) - (y4-y3)*(x1-x3)) / ((y4-y3)*(x2-x1) - (x4-x3)*(y2-y1));
  float uB = ((x2-x1)*(y1-y3) - (y2-y1)*(x1-x3)) / ((y4-y3)*(x2-x1) - (x4-x3)*(y2-y1));
```

i'm not entirely sure what any of this operations intends but i'll do my best to split them

2024-07-22 21:14 UTC, agustinesco commented on client/Assets/Scripts/CollisionDetection.cs
> +    Position otherLineSecondVertex = other_line.vertices[1];
force of habit :P as i mentioned i intended to leave this pr as a draft so i'll fix this now

2024-07-22 22:53 UTC, agustinesco commented on client/Assets/Scripts/CollisionDetection.cs
> +                result.Add(obstacleGameEntity.id);
1. I ended up using a dictionary to store a tuple containing both entities' shapes as keys and for the value we store a lambda that will call the proper function, I think the readability of this way is good, let me know what you think!
2. hmm idk about changing the collision check behavior, every check function uses another one, and ends up in a long chain of passing the result list between functions, I think the way it's is readable enough. We can talk about this

2024-07-23 15:36 UTC, Nico-Sanchez commented on client/Assets/Scripts/CollisionDetection.cs
> +                result.Add(obstacleGameEntity.id);
2. Ok, it's a bigger refactor than I expected.

Let's ask about the performance of 1 lambda functions.

2024-07-23 15:38 UTC, Nico-Sanchez commented on client/Assets/Scripts/CollisionDetection.cs
> +        / Math.Pow(line_length, 2);
Yeah I thought so, I understand the math in it.
What I meant is to change the variable name:
> don't call it dot please, that's a different thing.
Don't call it dotProduct either. As I said before, name the variables after what they represent.

For example, it could be:
`float dotProductBetweenLineAndCircle = ( ((cx-x1)*(x2-x1)) + ((cy-y1)*(y2-y1)) ) / pow(len,2);`

Of course this is something I made up, replace the name with what it represents.

2024-07-23 16:50 UTC, Nico-Sanchez commented on client/Assets/Scripts/CollisionDetection.cs
> +    return uA >= 0.0f || uA <= 1.0f &&  uB >= 0.0f || uB <= 1.0f;
It's ok. It's hard to name this kind of math. Looks much better now 😄

2024-07-23 16:54 UTC, Nico-Sanchez commented on client/Assets/Scripts/CollisionDetection.cs
> +public static bool LineCircleCollision(GameEntity line, GameEntity circle) {
All these collision check functions should be called after an action (with a verb). This way, the boolean returned is easy to understand without checking the function code.

2024-07-23 17:23 UTC, agustinesco commented on client/Assets/Scripts/CollisionDetection.cs
> +        / Math.Pow(line_length, 2);
I think `lineAndCircleDotProduct` is a suitable name

2024-07-23 17:24 UTC, agustinesco commented on client/Assets/Scripts/CollisionDetection.cs
> +                result.Add(obstacleGameEntity.id);
Every time you declare a lambda c# allocate some memory to save the variable states to run it after, so yeah they'll negatively affect the performance, i restore the if chain since it's not that hard to read and it's performant enough

2024-07-23 17:25 UTC, agustinesco commented on client/Assets/Scripts/CollisionDetection.cs
> +public static bool LineCircleCollision(GameEntity line, GameEntity circle) {
Done! i rephrase them to `AreShape1AndSapre2Colliding`

2024-07-23 17:46 UTC, Nico-Sanchez submitted a review, later dismissed

2024-07-23 17:51 UTC, Nico-Sanchez submitted a review, later dismissed

2024-07-25 18:32 UTC, Nico-Sanchez commented
Sometimes the client and the backend doesn't solve the collision the same way.
We can merge this and fix it in another PR if it's not quick, since this is already a step forward in our fix.

https://github.com/user-attachments/assets/5268a577-09f6-4809-a9c6-212313a6d400

2024-07-25 18:58 UTC, agustinesco commented
> Sometimes the client and the backend doesn't solve the collision the same way. We can merge this and fix it in another PR if it's not quick, since this is already a step forward in our fix.
> 
>  Screen.Recording.2024-07-25.at.3.26.44.PM.mov

There's no easy solution for this issue, since this variance in push direction is due to the position in the front

2024-07-26 22:14 UTC, Nico-Sanchez submitted a review, later dismissed

2024-07-29 16:34 UTC, tvillegas98 commented on client/Assets/Scripts/CollisionDetection.cs
> +                Debug.Log("collide circle polygon" + obstacleGameEntity.id);
```suggestion
```

2024-07-29 16:34 UTC, tvillegas98 commented on client/Assets/Scripts/CollisionDetection.cs
> +                Debug.Log("collide polygon" + obstacleGameEntity.id);
```suggestion
```

2024-07-29 16:36 UTC, tvillegas98 requested changes
Great work with this code migration! so sad that we can't fix small difference between client and server.
Left some comments to remove some logs

2024-07-29 17:58 UTC, tvillegas98 approved these changes

2024-07-29 19:06 UTC, Nico-Sanchez approved these changes

2024-07-29 19:06 UTC, merged