[VFX] Bushes Hide effect
lambdaclass/champions_of_mirra pull request #1982
Opened 2024-07-23 21:39 UTC by saugon

Based on: https://github.com/lambdaclass/champions_of_mirra/pull/1958

## Motivation

Added bushes with the dither shader, a character shader with the dither feature, and a controller to enable/disable these features using colliders. The colliders can be switched to anything else necessary on the server. this request contains unified character shader.
It’s also good to set up the collision matrix for the new "Hide" layer, as shown in the screen below, to use colliders more efficiently.
![зображення](https://github.com/user-attachments/assets/6513b967-6128-4c15-9e30-6bcc3ac25367)

## Summary of changes

Added bushes and their shader, unified character shader, and dither controller.

## How has this been tested?

This effect can be teste via test scene by manualy moving Muflus throgh the bushes

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-07-24 13:29 UTC, saugon commented
ℹ️ The logic in CharacterHideController is only for testing purposes, not the actual logic that will be implemented

2024-07-24 19:40 UTC, tkz00 submitted a review, later dismissed
Great! Works and looks good, although where the shader becomes kind of transparent they look kind of like squares, which I'm not 100% on board with but beyond that it looks good and works fine on android!

Also it was pretty interesting to learn that you can have the camera position as an input for a shader.

2024-07-25 20:59 UTC, AngieDutra requested changes

2024-07-25 20:59 UTC, AngieDutra commented on client/Assets/Prefabs/Characters/Muflus.prefab
A broken script was added to muflus's prefab
<img width="461" alt="Screenshot 2024-07-25 at 17 54 37" src="https://github.com/user-attachments/assets/19bf67e5-8c69-411a-b18a-3bc8380a748b">

2024-07-25 20:59 UTC, AngieDutra commented on client/Assets/Prefabs/Camera/BattleCameraUI.prefab
I don't know if we want to add that label in the culling mask of the camera yet since we have yet to implement this feature
<img width="448" alt="Screenshot 2024-07-25 at 17 58 02" src="https://github.com/user-attachments/assets/735314ef-91fe-4364-a133-47537f93a806">

2024-07-25 21:47 UTC, AngieDutra commented on client/Assets/Prefabs/Characters/Muflus.prefab
Solved this restoring muflus. No need to change this prefab in this PR

2024-07-25 21:48 UTC, AngieDutra commented on client/Assets/Prefabs/Camera/BattleCameraUI.prefab
TL @saugon expressed there is no need to change this. It won't affect our current game

2024-07-25 21:48 UTC, AngieDutra approved these changes
Awesome

2024-07-26 14:31 UTC, tkz00 approved these changes

2024-07-26 14:31 UTC, merged