[VFX] Added Kenzu Skills effects
lambdaclass/champions_of_mirra pull request #1984
Opened 2024-07-24 14:00 UTC by saugon

Based on: https://github.com/lambdaclass/champions_of_mirra/pull/1823

## Motivation

I’ve added Kenzu Skill1 basic attack effects, the Ultimate effect, and 4 Dash effects, along with a test scene and a cheat panel for testing. The request contains test code in PinnedEffectsController.cs that needs to be removed before merging.

## Summary of changes

Added Kenzu Skill1 basic attack effects, Ultimate effect and 4 Dash effects, test scene and cheat panel for testing.

## How has this been tested?

Effects could be tested via cheat panel in test scene or via generic gameplay

## Checklist
- [ ] I have tested the changes locally.
- [ ] I have tested the whole game after applying the changes, not only the affected areas.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

2024-07-25 14:23 UTC, tkz00 requested changes
Also I'm not a fan of the shield VFX for Kenzu's ultimate skill, is that something to be taken into account here?

![Screenshot_20240725_111324_client](https://github.com/user-attachments/assets/a37afd24-b55d-4bbb-83f3-5b0f864133b5)

2024-07-25 14:23 UTC, tkz00 commented on client/Assets/Scripts/Effects/PinnedEffectsController.cs
> +        pinned_effects_manager = FindFirstObjectByType<PinnedEffectsManager>();// FOR TEST CASES ONLY! REMOVE BEFORE MERGE
Should we remove this?

2024-07-25 14:24 UTC, tkz00 commented on client/Assets/Scripts/Effects/PinnedEffectsController.cs
> +        pinned_effects_manager = FindFirstObjectByType<PinnedEffectsManager>();// FOR TEST CASES ONLY! REMOVE BEFORE MERGE
Based on the description of the PR

2024-07-25 14:44 UTC, saugon commented on client/Assets/Scripts/Effects/PinnedEffectsController.cs
> +        pinned_effects_manager = FindFirstObjectByType<PinnedEffectsManager>();// FOR TEST CASES ONLY! REMOVE BEFORE MERGE
Yes, definitely!

2024-07-25 14:46 UTC, tkz00 commented on client/Assets/Scripts/Effects/PinnedEffectsController.cs
> +        pinned_effects_manager = FindFirstObjectByType<PinnedEffectsManager>();// FOR TEST CASES ONLY! REMOVE BEFORE MERGE
```suggestion
        
```

2024-07-25 16:59 UTC, tkz00 commented on client/Assets/Scripts/Effects/PinnedEffectsController.cs
> +        pinned_effects_manager = FindFirstObjectByType<PinnedEffectsManager>();// FOR TEST CASES ONLY! REMOVE BEFORE MERGE
Great!

2024-07-25 17:00 UTC, tkz00 approved these changes
Great! The effects look amazing and the test scene works great on my android.

2024-07-25 20:35 UTC, AngieDutra requested changes
Tried restarting Unity but I think this bug is here in this PR:
I can't die with muflus in the game because of the following
<img width="750" alt="Screenshot 2024-07-25 at 17 27 07" src="https://github.com/user-attachments/assets/0dbf0d13-7c65-4172-afb8-78d8497d79b4">
<img width="511" alt="Screenshot 2024-07-25 at 17 27 15" src="https://github.com/user-attachments/assets/43edf895-b812-47a9-9584-fafbe800a0ee">
<img width="447" alt="Screenshot 2024-07-25 at 17 32 59" src="https://github.com/user-attachments/assets/a5205280-19aa-4551-8044-5e06c3a4fb02">
All characters have lost their pick up item effect reference and their death feedback reference

2024-07-25 22:23 UTC, AngieDutra approved these changes
Nice ✅ 
I want kenzu in the game asap! He looks cool 🐱

2024-07-26 15:15 UTC, tkz00 approved these changes

2024-07-26 15:16 UTC, merged