add image to readme
lambdaclass/champions_of_mirra pull request #237
Opened 2024-03-06 20:44 UTC by salvadorstrambini

Closes #[issue]

## Motivation

Estoy practicando como agregar una imagen al readme de champions of mirra

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-03-15 21:03 UTC, AngieDutra requested changes
Apart from your PR, we have broken links in main. Maybe just delete those lines to have a tidier read me. We can add more images later. The following lines should be deleted:

```
<div>
  <div float="center">
    <img src="docs/src/images/Curse_of_Myrra_3D_Assets_Muflus.png" alt="Muflus 3D model" width=300px>  
    <img src="docs/src/images/Curse_of_Myrra_3D_Assets_Uma.jpeg" alt="Uma 3D model" width=300px> 
  </div>
  <div float="center">
    <img src="docs/src/images/Curse_of_Myrra_concept_art_Shinko.png" alt="Shinko hero concept art" width=300px>
    <img src="docs/src/images/Curse_of_Myrra_concept_art_Otobi_dog.png" alt="Concept art for a gang member dog in the planet of Otobi" width=300px>
  </div>
<div>
```

2024-03-15 21:03 UTC, AngieDutra commented on IMG_9706.PNG
Avoid unclear names for any type of file. Maybe "ChampionsBattle" is a good name for this image

2024-03-15 21:03 UTC, AngieDutra commented on IMG_9706.PNG
This file should be inside of a "docs" folder

2024-03-15 21:06 UTC, AngieDutra commented on IMG_9706.PNG
Just an observation you should add the docs path if you create the folder requested. The readme addition would be:
`<img src="docs/ChampionsBattle.png" alt="Champions Banner">`

2024-03-16 02:44 UTC, salvadorstrambini commented on IMG_9706.PNG
Ok thanks

2024-03-16 02:45 UTC, salvadorstrambini commented on IMG_9706.PNG
Done. I think is alright now. Thank you

2024-03-19 22:18 UTC, AngieDutra approved these changes
Good one!

2024-03-20 21:24 UTC, ncontinanza approved these changes
Nice!

2024-03-21 00:14 UTC, merged