Level progression
lambdaclass/champions_of_mirra pull request #268
Opened 2024-03-14 20:19 UTC by tkz00

When a level is beaten the next level will be unlocked to battle, while the beaten levels will be unavailable as indicated by a red cross. Progression between campaigns is still not available.

2024-03-14 21:31 UTC, ncontinanza requested changes
Level progression is working fine, but there are some things I noticed when testing with the demo branch from the backend:
- The scrolls currency amount is not being shown in the header
- I couldn't find the buttons to summon a character in the summon scene.

2024-03-15 14:00 UTC, tkz00 commented
> Level progression is working fine, but there are some things I noticed when testing with the demo branch from the backend:
> 
>     * The scrolls currency amount is not being shown in the header
> 
>     * I couldn't find the buttons to summon a character in the summon scene.

Good catch, fixed with the last commit. There was a discrepancy between the names of currencies in the client and the backend.

2024-03-15 15:23 UTC, ncontinanza approved these changes

2024-03-15 20:32 UTC, AngieDutra approved these changes
Tested and worked just fine! Noticed some game flow issues but I'll create issues for those

2024-03-15 20:42 UTC, merged