Go next after beating level
lambdaclass/champions_of_mirra pull request #296
Opened 2024-03-22 20:38 UTC by tkz00

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-03-25 05:02 UTC, AngieDutra requested changes
Tested and works as expected! Just a few comments:
Unity has a cool feature of "Safe area". This yellow line represents the area that will always display as visible and interactive in any phone. Leaving info outside this area is a risky move. I recommend moving the "Tap to return" text under the button. Although, leave a bit of space in between, so it doesn't get overpowered by the button in visual terms.
<img width="250" alt="Captura de pantalla 2024-03-25 a la(s) 1 47 44 a  m" src="https://github.com/lambdaclass/champions_of_mirra/assets/82987608/97e4da5d-2dcf-4c1f-9ae5-ff613e8b9fb1">

Also, watch out with this button size. The following shouldn't happen. Maybe add with to the button in this case. It's actually a different type of button that takes the user back to another scene. Maybe use the secondary button to move from each leven and use this primary one when the user defeats the boss and it's given the option to move to the next campaign 
<img width="207" alt="Captura de pantalla 2024-03-25 a la(s) 1 51 49 a  m" src="https://github.com/lambdaclass/champions_of_mirra/assets/82987608/e3719538-028d-41ff-822a-545f18e26457">

2024-03-25 19:31 UTC, tkz00 commented
> Tested and works as expected! Just a few comments: Unity has a cool feature of "Safe area". This yellow line represents the area that will always display as visible and interactive in any phone. Leaving info outside this area is a risky move. I recommend moving the "Tap to return" text under the button. Although, leave a bit of space in between, so it doesn't get overpowered by the button in visual terms. <img alt="Captura de pantalla 2024-03-25 a la(s) 1 47 44 a  m" width="250" src="https://private-user-images.githubusercontent.com/82987608/316390467-97e4da5d-2dcf-4c1f-9ae5-ff613e8b9fb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTQ3MzcsIm5iZiI6MTcxMTM5NDQzNywicGF0aCI6Ii84Mjk4NzYwOC8zMTYzOTA0NjctOTdlNGRhNWQtMmRjZi00YzFmLTlhZTUtZmY2MTNlOGI5ZmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE5MjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMTIxMmM5YzY1OTI1MTc2NDIzNGM4NDMwOGRjMzAxNzZhZmQ5MzQ1MTg4YTdiMTU2Mzc5NTJkYTcyY2VjYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iKMs3PdwYhUfUx4GeZMsBxIqmoZQIsmgXjKjfo0bBlg">
> 
> Also, watch out with this button size. The following shouldn't happen. Maybe add with to the button in this case. It's actually a different type of button that takes the user back to another scene. Maybe use the secondary button to move from each leven and use this primary one when the user defeats the boss and it's given the option to move to the next campaign <img alt="Captura de pantalla 2024-03-25 a la(s) 1 51 49 a  m" width="207" src="https://private-user-images.githubusercontent.com/82987608/316391775-e3719538-028d-41ff-822a-545f18e26457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTQ3MzcsIm5iZiI6MTcxMTM5NDQzNywicGF0aCI6Ii84Mjk4NzYwOC8zMTYzOTE3NzUtZTM3MTk1MzgtMDI4ZC00MWZmLTgyMmEtNTQ1ZjE4ZTI2NDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE5MjAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMzAxYTExZjJlZGRiNTBiN2ExYmU2MGJlMTg0ZWMxYWY5MzQxOWMxMTg2NjVkZDQ5ZDUxOGZmYWQxYzFmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2WwGHq5VnGreNnyYoUUcbJO1lZr9-zidN86u3Ul23I">

The "Tap to return" text has been moved inside the safe area, and the next campaign button text is handled in [this buttons redesign PR](https://github.com/lambdaclass/champions_of_mirra/pull/286).

2024-03-25 21:36 UTC, AngieDutra requested changes
Move the "Tap to return" up. It's still to low in the screen to be noticeable in time

2024-03-25 22:03 UTC, AngieDutra submitted a review, later dismissed
Looks awesome! ✨

2024-04-04 18:05 UTC, martinacantaro commented
Tested and all three changes are approved. 
The only thing is that the unit list in the battle screen overlaps with the Back and Battle buttons

<img width="378" alt="Screenshot 2024-04-04 at 15 03 41" src="https://github.com/lambdaclass/champions_of_mirra/assets/6120897/82e0d4a2-5914-473d-923e-a26ee8028279">

2024-04-04 18:28 UTC, tkz00 commented
> Tested and all three changes are approved. The only thing is that the unit list in the battle screen overlaps with the Back and Battle buttons
> <img alt="Screenshot 2024-04-04 at 15 03 41" width="378" src="https://private-user-images.githubusercontent.com/6120897/319719591-82e0d4a2-5914-473d-923e-a26ee8028279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNTUzOTEsIm5iZiI6MTcxMjI1NTA5MSwicGF0aCI6Ii82MTIwODk3LzMxOTcxOTU5MS04MmUwZDRhMi01OTE0LTQ3M2QtOTIzZS1hMjZlZTgwMjgyNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTgyNDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTY4MTBhZTcyNzFiOGY5NmY3M2ExZWYyZjU4ZmZkMmRkY2JiZTBiMjg2NjZkYTFjMDJlYWYzNmNjZjc3NWY2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PRPaGnjA9krvP6whaLmjO1lgDcCujWP0oTjYngin3AQ">

Good catch, fixed!

2024-04-04 20:10 UTC, ncontinanza requested changes

2024-04-05 19:23 UTC, tkz00 commented on client/Assets/Scripts/Campaign/CampaignLevelsManager.cs
> +        for(int levelIndex = 0; levelIndex < levelsData.Count; levelIndex++) {
Modified this

2024-04-08 17:08 UTC, ncontinanza approved these changes
LGTM!

2024-04-08 17:10 UTC, merged