Refactor campaign progression
lambdaclass/champions_of_mirra pull request #314
Opened 2024-04-03 20:00 UTC by tkz00

Backend PR: https://github.com/lambdaclass/mirra_backend/pull/415

Closes https://github.com/lambdaclass/champions_of_mirra/issues/193

## Motivation

The progress of a player is now a new message from the backend, instead of coming with the user. This PR implements this new communication. Also the campaigns progresses now hold a super campaign id as well as a level and campaign id, this isn't currently used, but will in the future when multiple campaigns are accessible.

## Summary of changes

When getting a user, another call to the backend is made retrieving the campaigns progresses.

## How has this been tested?

Play through levels normally and check the progression works as expected.

2024-04-04 14:36 UTC, lotuuu submitted a review, later dismissed

2024-04-04 19:17 UTC, ncontinanza requested changes

2024-04-04 19:17 UTC, ncontinanza commented on client/Assets/Scripts/BackendConnection/SocketConnection.cs
> +	public void GetCampaignsProgress(string userId, Action<List<(string, string, string)>> onCampaignProgressReceived)
Would the name `GetCampaignProgresses` be more consistent with the rest of the names used here and in the context in which this method is called?

2024-04-04 19:20 UTC, tkz00 commented on client/Assets/Scripts/BackendConnection/SocketConnection.cs
> +	public void GetCampaignsProgress(string userId, Action<List<(string, string, string)>> onCampaignProgressReceived)
Yeah, it really makes sense. The change is made!

2024-04-04 19:31 UTC, ncontinanza submitted a review, later dismissed
LGTM!

2024-04-05 15:15 UTC, martinacantaro commented
doesn't LGTM :( 

When I go to the Campaign screen for the first time, campaigns 1 and 2 appear as completed even though I never played them. 

<img width="408" alt="Screenshot 2024-04-05 at 12 14 44" src="https://github.com/lambdaclass/champions_of_mirra/assets/6120897/411344ac-ad59-4f48-acc3-8ee07df6375b">

2024-04-05 19:13 UTC, martinacantaro requested changes
Please fix

2024-04-08 20:09 UTC, tkz00 commented
> doesn't LGTM :(
> 
> When I go to the Campaign screen for the first time, campaigns 1 and 2 appear as completed even though I never played them.
> 
> One detail to note is that in the several times I shut down the devenv and restarted it, one of those times it magically worked. But 99% of the time it didn't.
> <img alt="Screenshot 2024-04-05 at 12 14 44" width="408" src="https://private-user-images.githubusercontent.com/6120897/320050753-411344ac-ad59-4f48-acc3-8ee07df6375b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MDcxNTIsIm5iZiI6MTcxMjYwNjg1MiwicGF0aCI6Ii82MTIwODk3LzMyMDA1MDc1My00MTEzNDRhYy1hZDU5LTRmNDgtYWNjMy04ZWUwN2RmNjM3NWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMjAwNzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjcyNzJhZjZhNGVkY2IyMjQxMmFmNTRmN2VlNWQxZTNkNmZmY2Q5YTM3NmIzOTUzYzQ5OGU5ZDYzNGRiZGFmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Yf43M1xVrkBKnKQTMTkyLqvPedblPiinMj-LushN4cU">

Found the bug and fixed it!

2024-04-08 20:36 UTC, lotuuu approved these changes
Worked great for me! Nice job!

2024-04-08 21:46 UTC, ncontinanza approved these changes

2024-04-10 17:01 UTC, martinacantaro approved these changes
lgtm

2024-04-10 17:01 UTC, merged