Health bar battle feedback
lambdaclass/champions_of_mirra pull request #324
Opened 2024-04-04 19:40 UTC by tkz00

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-04-11 15:40 UTC, martinacantaro commented
The simulation battle is 12 mufluses hitting each other at the same time. Every unit receives 50 damage each round, at the same time. But in the health bar I see some characters losing more health with each hit than others.

Let's assign numbers to each unit according to their position on screen, from top left to bottom right, like so:

1 --- 2 ---------- 3 --- 4

5 --- 6 ---------- 7 --- 8

9 --- 10 --------- 11 -- 12

I see unit 10 losing health much faster than all the others.
In step 3 it has lost all its health while most of the others have more than half left.
Then in step 4 unit 10 dies,  and unit 9 suddenly loses more than half of its total health in the bar. This seems to happen in two health drops during the same step, if you look closely at the video. At this step you can see a vast difference between the health of different units (screenshot below)

https://github.com/lambdaclass/champions_of_mirra/assets/6120897/baedbed8-e969-4e20-9f60-84dcc87ab1a3

<img width="438" alt="Screenshot 2024-04-11 at 12 39 53" src="https://github.com/lambdaclass/champions_of_mirra/assets/6120897/cb6b9026-30be-43c5-84fb-8ebf06348745">

2024-04-11 15:41 UTC, martinacantaro requested changes
see comment above ☝️

2024-04-11 17:36 UTC, tkz00 commented
> The simulation battle is 12 mufluses hitting each other at the same time. Every unit receives 50 damage each round, at the same time. But in the health bar I see some characters losing more health with each hit than others.
> 
> Let's assign numbers to each unit according to their position on screen, from top left to bottom right, like so:
> 
> 1 --- 2 ---------- 3 --- 4
> 
> 5 --- 6 ---------- 7 --- 8
> 
> 9 --- 10 --------- 11 -- 12
> 
> I see unit 10 losing health much faster than all the others. In step 3 it has lost all its health while most of the others have more than half left. Then in step 4 unit 10 dies, and unit 9 suddenly loses more than half of its total health in the bar. This seems to happen in two health drops during the same step, if you look closely at the video. At this step you can see a vast difference between the health of different units (screenshot below)
> Screen.Recording.2024-04-11.at.12.31.49.mov
> <img alt="Screenshot 2024-04-11 at 12 39 53" width="438" src="https://private-user-images.githubusercontent.com/6120897/321694086-cb6b9026-30be-43c5-84fb-8ebf06348745.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTY5MzQsIm5iZiI6MTcxMjg1NjYzNCwicGF0aCI6Ii82MTIwODk3LzMyMTY5NDA4Ni1jYjZiOTAyNi0zMGJlLTQzYzUtODRmYi04ZWJmMDYzNDg3NDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTczMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjcwZDdlMmZkMTkyOTRlMTI1ZDIzODE4YjY5M2MzOGNjZDQ4ZjQwOWFhYTJjYTI3NzBlNzY3MGJlNmY0N2RhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3tWJxaiJptzfr7ZMTjBbauNOwhNZn_gL45b55QVnwEU">

The targeting of the attack of each unit is random, that's why in some steps some units take more damage and others don't, and that random factor is what changes the outcome of the battle, winning some times and others loosing.

2024-04-11 17:50 UTC, martinacantaro commented
Understood, so from the UX the text that shows the damage text appears different from what the health bar shows. All of them say -50 but some units have in fact multiple stacked "-50s", which appear as only one message because they are overlapping.

This is fine for now, but I will open a ticket to fix this after pre-Alpha

2024-04-11 17:50 UTC, martinacantaro submitted a review, later dismissed

2024-04-11 19:48 UTC, martinacantaro commented
per the comment above https://github.com/lambdaclass/champions_of_mirra/issues/347

2024-04-12 14:16 UTC, martinacantaro approved these changes
tested it again, still working fine!

2024-04-12 18:52 UTC, ncontinanza requested changes

2024-04-12 18:52 UTC, ncontinanza commented on client/Assets/Scripts/BackendConnection/SocketConnection.cs
> +		// // Create a new BattleReplay instance
Is this commented code something that we should keep?

2024-04-12 18:52 UTC, ncontinanza commented on client/Assets/Scripts/Battle/BattleManager.cs
> +		#region Play Out Battle
Do you think we could break this into smaller methods to make it more readable and easier to understand?

2024-04-12 18:52 UTC, ncontinanza commented on gateway.proto
> +    defense = 3;
These should be uppercase

2024-04-12 18:55 UTC, ncontinanza requested changes

2024-04-12 18:55 UTC, ncontinanza commented on client/Assets/Scripts/Battle/BattleManager.cs
> +			// for(int i = 0; i < battleReplay.InitialState.Units.Count; i++)
Is this commented code necessary?

2024-04-12 20:40 UTC, tkz00 commented on client/Assets/Scripts/Battle/BattleManager.cs
> +			// for(int i = 0; i < battleReplay.InitialState.Units.Count; i++)
Deleted!

2024-04-12 20:40 UTC, tkz00 commented on gateway.proto
> +    defense = 3;
Fixed!

2024-04-12 20:40 UTC, tkz00 commented on client/Assets/Scripts/Battle/BattleManager.cs
> +		#region Play Out Battle
You're right, those regions have been changed into separate methods!

2024-04-12 20:41 UTC, tkz00 commented on client/Assets/Scripts/BackendConnection/SocketConnection.cs
> +		// // Create a new BattleReplay instance
Deleted

2024-04-12 21:20 UTC, ncontinanza approved these changes
LGTM!
I opened this issue to refactor the BattleManager later: https://github.com/lambdaclass/champions_of_mirra/issues/353

2024-04-15 17:39 UTC, tkz00 commented
> LGTM! I opened this issue to refactor the BattleManager later: #353

Great Nico! Just saw to comment! Many thanks!

2024-04-15 18:29 UTC, marco-paulucci approved these changes
LGTM, great work!

2024-04-15 18:30 UTC, merged