Death animation battle feedback
lambdaclass/champions_of_mirra pull request #349
Opened 2024-04-11 20:52 UTC by tkz00

Closes #348 
Wait for [Health bar battle feedback](https://github.com/lambdaclass/champions_of_mirra/pull/324) to be merged

## Motivation

The user needs to understand that a unit has died in the battle.

## Summary of changes

A new action type case is handled in the battle manager, the death of a unit, this triggers an animation for the respective battle unit where it rotates 90° and fades out.

## How has this been tested?

Play out a battle simulation and check when a unit's health reaches 0 it falls over and disappears.

2024-04-12 14:20 UTC, martinacantaro submitted a review, later dismissed
marvelous

2024-04-16 15:26 UTC, martinacantaro approved these changes
tried battling different levels up to campaign 2 level 1, and it works fine!

2024-04-16 21:08 UTC, martinacantaro submitted a review, later dismissed
tested and approved again

2024-04-17 19:21 UTC, ncontinanza requested changes
looking great! Just a few comments about the code and we're good to go

2024-04-17 19:21 UTC, ncontinanza commented on client/Assets/Scripts/Battle/BattleManager.cs
> +								Color porjectileColor;
```suggestion
								Color projectileColor;
```

2024-04-17 19:21 UTC, ncontinanza commented on client/Assets/Scripts/Battle/BattleManager.cs
> +								Color porjectileColor;
Also change it where it's being used

2024-04-17 19:21 UTC, ncontinanza commented on client/Assets/Scripts/Battle/BattleManager.cs
> +												// playerUnitsUI.Concat(opponentUnitsUI).First(unit => unit.SelectedUnit.id == action.SkillAction.CasterId).AttackFeedback(targetUnit.transform.position);
Can this comment be removed?

2024-04-17 19:21 UTC, ncontinanza commented on client/Assets/Scripts/Battle/ProjectilesPooler.cs
> +    public void ShootProjectile(Transform startTransform, Transform targetTransform, Color porjectileColor) {
```suggestion
    public void ShootProjectile(Transform startTransform, Transform targetTransform, Color projectileColor) {
```

2024-04-19 14:13 UTC, martinacantaro approved these changes
approved! they're dropping like flies 🪰

2024-04-19 14:46 UTC, ncontinanza approved these changes
LGTM!

2024-04-19 14:51 UTC, merged