Projectiles glow on hit
lambdaclass/champions_of_mirra pull request #361
Opened 2024-04-17 16:00 UTC by tkz00

Closes #354 
⚠️ Goes together with backend PR: [Refactor Gateway Messages](https://github.com/lambdaclass/mirra_backend/pull/473)

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-04-23 15:19 UTC, martinacantaro approved these changes
Functional review approved.
After I set an initial_delay higher than 0 in the skills.json config, I was able to see the transparency between targeting and on_hit

2024-04-23 15:31 UTC, martinacantaro approved these changes
Approved again after the conflict fix

2024-04-23 17:17 UTC, ncontinanza requested changes

2024-04-23 17:17 UTC, ncontinanza commented on client/Assets/Scripts/Battle/BattleManager.cs
> +			}
This duplicate code could be abstracted into another method

2024-04-24 19:58 UTC, tkz00 commented on client/Assets/Scripts/Battle/BattleManager.cs
> +			}
Yess! You are right, this has been fixed, and the code reordered a bit to improve clarity and redeability.

2024-04-24 21:42 UTC, ncontinanza approved these changes

2024-04-24 21:45 UTC, martinacantaro approved these changes
functional review approved!

2024-04-24 21:45 UTC, merged