Kaline tree level up
lambdaclass/champions_of_mirra pull request #376
Opened 2024-04-22 22:02 UTC by ncontinanza

Closes #374 

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-04-24 21:09 UTC, martinacantaro approved these changes
Functional review approved 👍 
For the next PR, please add the Tree level in the frontend

2024-04-25 15:39 UTC, lotuuu requested changes
There's a bug on the level up cost. When I'm not able to level up any more, if I get out of the scene and back in, the level up cost is reset to the amount it displayed when I go into it.


https://github.com/lambdaclass/champions_of_mirra/assets/31993243/0815c10f-3a19-4343-a648-d194814fba13

2024-04-25 16:01 UTC, ncontinanza commented on gateway.proto
> +    uint64 fertilizer_level_up_cost = 3;
As far as I checked, we do not. Probably because we're not receiving that info from the backend, I'll create an issue for that

2024-04-25 16:47 UTC, lotuuu submitted a review, later dismissed

2024-04-25 16:53 UTC, martinacantaro submitted a review, later dismissed
Re-tested via frontend and backend commands. Functional review approved!

2024-04-25 17:58 UTC, tkz00 requested changes
Great, works amazing. Just one thing, fields should be named using camelCase, not snake_case, according to the project's and C#'s conventions.

2024-04-25 18:57 UTC, tkz00 approved these changes
Amazing!

2024-04-25 20:00 UTC, martinacantaro approved these changes
approved once again

2024-04-25 20:01 UTC, merged