In game server selector
lambdaclass/champions_of_mirra pull request #379
Opened 2024-04-24 13:04 UTC by tkz00

Closes #344 

## Motivation

A runtime way to change the server to be connected is needed, in production it will serve the user to play on different servers, but the feature is introduced now since it's useful for testing during the development, specially now the mobile build is close, since previous to this feature to test different servers on a phone you needed to edit source code an rebuild the app, which takes an enormous amount of time.

## Summary of changes

Added a server button on the overworld scene, which describes the current server the user is corrected, selecting this button opens up a popup which let's you choose between localhost and europe servers, also letting you introduce a custom server domain and choose that to connect. All this functionality is handled by the `SelectServer.cs` script.

Consider now a `userId` is saved in player prefs for each server, so starting in local, changing to Europe and coming back to local will maintain you original local user (the user won't be shared between Europe and local), to stop this you can delete the user from the database or clear up the player prefs from the Unity editor, the second way is simpler but you delete the user id's from all the servers, you can't just delete one.

## How has this been tested?

Start the application and try to change servers, consider currently the only "production" server available is the Europe one, so you need at least one local server running, verify no exceptions appear and your user is created/brought from the backend. If possible also try to connect to your local server exposing the address through ngrok via the custom server address.

2024-04-29 17:08 UTC, ncontinanza requested changes
The problem of registering the user is solved (that was because of the seeds not being run in the backend), but I'm still getting several errors when trying to run a battle or summon a unit.

https://github.com/lambdaclass/champions_of_mirra/assets/17294394/93b061ac-0554-475c-9856-93fbea6ac5d1

2024-05-06 13:52 UTC, tkz00 commented
> The problem of registering the user is solved (that was because of the seeds not being run in the backend), but I'm still getting several errors when trying to run a battle or summon a unit.
> Screen.Recording.2024-04-29.at.14.02.44.mov

Nice catch Nico! This has been addressed!

2024-05-06 14:37 UTC, ncontinanza requested changes

2024-05-06 14:37 UTC, ncontinanza commented on client/Assets/Scripts/BackendConnection/ServerSelect.cs
> +			// ServerSelect.Domain = servers["EUROPE"];
```suggestion
```

2024-05-13 15:13 UTC, lotuuu approved these changes

2024-05-13 15:13 UTC, lotuuu commented
Later on we might want to put the Server Select option before actually creating connections, to prevent possible bugs

2024-05-13 15:29 UTC, merged