Client backend connection
lambdaclass/champions_of_mirra pull request #39
Opened 2023-12-24 22:46 UTC by tkz00

This PR makes the client communicate with the backend for unit & battle related functionalities. These are:
- Getting the player units in UnitList & Lineup scenes.
- Selecting & unselecting units in the Lineup scene.
- Getting a battle to run in the backend, receive the winner & display the according splash screen in Battle scene.

The communication is handled through the BackendConnection class which has the calls to all the endpoints. This class is utilized by different managers in each respective scene to communicate with the backend.

Important note: while the BackendConnection class methods receive the respective user id's as parameters, the way these methods are called currently is with hardcoded id's, which must be changed to match the ones generated on your database.

2023-12-27 18:58 UTC, martinacantaro commented
Due to our open source license, for this repo we're not committing any third-party assets. Instead, for each third-party dependency that a PR adds, we include a change to the Readme adding this under the Dependencies section, and we also inform of them in the PR description so reviewers can download them. Please make the necessary changes

2023-12-27 19:06 UTC, martinacantaro commented
> Important note: while the BackendConnection class methods receive the respective user id's as parameters, the way these methods are called currently is with hardcoded id's, which must be changed to match the ones generated on your database.

Are these the "doinb_device" and "faker_device"?

Right now, both throw an error

```
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /users-characters/doinb_device/get_units (DarkWorldsServerWeb.Router)
    (dark_worlds_server 0.1.0) deps/phoenix/lib/phoenix/router.ex:489: DarkWorldsServerWeb.Router.call/2
    (dark_worlds_server 0.1.0) lib/dark_worlds_server_web/endpoint.ex:1: DarkWorldsServerWeb.Endpoint.plug_builder_call/2
    (dark_worlds_server 0.1.0) deps/plug/lib/plug/debugger.ex:136: DarkWorldsServerWeb.Endpoint."call (overridable 3)"/2
    (dark_worlds_server 0.1.0) lib/dark_worlds_server_web/endpoint.ex:1: DarkWorldsServerWeb.Endpoint.call/2
    (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
    (cowboy 2.10.0) /Users/martina/game_backend/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.10.0) /Users/martina/game_backend/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.10.0) /Users/martina/game_backend/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3

[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /users-characters/faker_device/get_units (DarkWorldsServerWeb.Router)
    (dark_worlds_server 0.1.0) deps/phoenix/lib/phoenix/router.ex:489: DarkWorldsServerWeb.Router.call/2
    (dark_worlds_server 0.1.0) lib/dark_worlds_server_web/endpoint.ex:1: DarkWorldsServerWeb.Endpoint.plug_builder_call/2
    (dark_worlds_server 0.1.0) deps/plug/lib/plug/debugger.ex:136: DarkWorldsServerWeb.Endpoint."call (overridable 3)"/2
    (dark_worlds_server 0.1.0) lib/dark_worlds_server_web/endpoint.ex:1: DarkWorldsServerWeb.Endpoint.call/2
    (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
    (cowboy 2.10.0) /Users/martina/game_backend/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.10.0) /Users/martina/game_backend/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.10.0) /Users/martina/game_backend/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3

```

2023-12-27 19:11 UTC, martinacantaro commented
Maridates with https://github.com/lambdaclass/game_backend/pull/125

2023-12-27 19:32 UTC, martinacantaro commented
I'm getting this 
```
.NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'error', line 1, position 9.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) (at <761cf2a144514d2291a678c334d49e9b>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value) (at <761cf2a144514d2291a678c334d49e9b>:0)
BackendConnection+<GetAvailableUnits>d__0.MoveNext () (at Assets/Scripts/BackendConnection/BackendConnection.cs:32)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPt
```

2023-12-27 20:15 UTC, martinacantaro commented
Closes https://github.com/lambdaclass/mirra_autobattler/pull/39

2023-12-31 20:23 UTC, martinacantaro requested changes

2023-12-31 20:23 UTC, martinacantaro commented on client/Assets/Scripts/BackendConnection/BackendConnection.cs
> +                    // errorCallback?.Invoke("USER_NOT_FOUND");
why is this line commented out?

2023-12-31 20:23 UTC, martinacantaro commented on client/Assets/Scripts/BackendConnection/BackendConnection.cs
> +                    // It would be nice to get the units ordered from the backend
please don't leave TODOs in comments, create a ticket for it. 
If there's a strong reason for leaving it in as a comment, always start with the word TODO for easy search. Otherwise it's unlikely to get noticed and fixed

2024-01-02 21:46 UTC, ncontinanza commented on client/Assets/Scripts/BackendConnection/BackendConnection.cs
> +                    // errorCallback?.Invoke("USER_NOT_FOUND");
I reckon that it was commented because the error callbacks were not implemented yet. By now, I added an error log for these cases, we can change it in the future if we need another behavior.

2024-01-03 15:17 UTC, ncontinanza commented on client/Assets/Scripts/Lineup/LineupManager.cs
> +    // change to centralized way to get Characters, so don't have to assign everytime
https://github.com/lambdaclass/champions_of_mirra/issues/50

2024-01-03 15:17 UTC, ncontinanza commented on client/Assets/Scripts/UnitList/UnitListManager.cs
> +    // change to centralized way to get Characters, so don't have to assign everytime
https://github.com/lambdaclass/champions_of_mirra/issues/50

2024-01-03 22:27 UTC, martinacantaro approved these changes

2024-01-03 22:27 UTC, merged