[GH-280] Display Energy bar in Battle
lambdaclass/champions_of_mirra pull request #420
Opened 2024-05-03 17:48 UTC by ncontinanza

Closes #280 

⚠️ Test together with this backend PR: https://github.com/lambdaclass/mirra_backend/pull/564

## Motivation

Until now, we couldn't see the energy accumulated by each unit in the battle. 

## Summary of changes

- Add an energy bar to the unit prefab, right below the health bar.
- Increase the energy level each time the unit attacks with the basic skill, and decrease the bar to zero when the ultimate skill is casted.
- Receive a new message from the backend, StatOverride, to support the case in which we need to set a specific value to a stat, such as setting it to zero when the energy is consumed to perform the ultimate attack. This message will be reused in the near future for other stats.

## How has this been tested?

Start the backend (use [this](https://github.com/lambdaclass/mirra_backend/pull/564) branch!) and fight a battle. You should see a blue energy bar above each unit's head, that increases with each use of the basic skill and decreases with each use of the ultimate skill (that is, after is reaches its top).

## Test additions / changes

List tests added/updated.

## Checklist
- [X] I have tested the changes locally.
- [X] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-05-03 19:08 UTC, tkz00 requested changes
https://github.com/lambdaclass/champions_of_mirra/assets/67983386/6aa45e44-7f73-4a34-8278-8db9edb4b120

I see that after casting their first ultimate of the battle, units stop charging it's energy bar, except sometimes that they charge a little and then it goes away without it being complete.

2024-05-07 16:28 UTC, ncontinanza commented
> Screen.Recording.2024-05-03.at.2.54.56.PM.mov 
> I see that after casting their first ultimate of the battle, units stop charging it's energy bar, except sometimes that they charge a little and then it goes away without it being complete.

Thanks! I wasn't limiting the amount to add/substract from the unit's energy, so in some cases I was allowing negative amounts of energy.

2024-05-10 19:17 UTC, tkz00 approved these changes

2024-05-14 15:11 UTC, tkz00 submitted a review, later dismissed

2024-05-15 20:11 UTC, tkz00 requested changes
Found an error when battling with less than 6 units in either team.

2024-05-15 20:11 UTC, tkz00 commented on client/Assets/Scripts/Battle/BattleManager.cs
> +						BattleUnit unit = battleUnitsUI.Single(unit => unit.SelectedUnit.id == action.EnergyRegen.TargetId);
```suggestion
						BattleUnit unit = battleUnitsUI.Single(unit => battleUnit.SelectedUnit != null && unit.SelectedUnit.id == action.EnergyRegen.TargetId);
```

This change allows the battle to play out with teams with less than 6 untis, we should really change this "search" behavior and encapsulate it in a single method.

2024-05-15 20:44 UTC, tkz00 commented on client/Assets/Scripts/Battle/BattleManager.cs
> +		BattleUnit target = battleUnitsUI.Single(unit => unit.SelectedUnit.id == action.StatOverride.TargetId);
```suggestion
						BattleUnit target = battleUnitsUI.Single(unit => unit.SelectedUnit != null && unit.SelectedUnit.id == action.StatOverride.TargetId);
```

Sorry, the same problem arrises here, it's the last one, I've checked.

2024-05-15 20:57 UTC, ncontinanza commented on client/Assets/Scripts/Battle/BattleManager.cs
> +		BattleUnit target = battleUnitsUI.Single(unit => unit.SelectedUnit.id == action.StatOverride.TargetId);
Nice catch!

2024-05-15 21:33 UTC, tkz00 approved these changes

2024-05-16 13:48 UTC, lotuuu requested changes

2024-05-16 13:48 UTC, lotuuu commented on client/Assets/Scripts/Battle/BattleManager.cs
> +				target.CurrentEnergy = Math.Max(0, (int)action.StatOverride.StatAffected.Amount);
Why are we introducing game logic here? If our battle design does not allow us to have negative energy, then it's not a good idea to hide it here, as the battle will be buggy and we will have less ways of finding out!

2024-05-16 14:14 UTC, lotuuu approved these changes

2024-05-16 17:36 UTC, tkz00 approved these changes

2024-05-16 17:37 UTC, merged