Unit list scene
lambdaclass/champions_of_mirra pull request #65
Opened 2024-01-05 21:17 UTC by ncontinanza

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-01-08 20:31 UTC, martinacantaro commented
- [ ] use a different button for "back" -> the one we've been using is the prefab called "Button (Back)", used in Lineup for example
- [ ] there's a small bug where it shows default text "USERNAME".
- [ ] When searching for a unity, it returns n-1 the amount of matches. e.g. There are two Muflus, but it only returns one. There are three Umas, but it only returns two.

2024-01-08 20:46 UTC, ncontinanza commented
> * [ ]  When searching for a unity, it returns n-1 the amount of matches. e.g. There are two Muflus, but it only returns one. There are three Umas, but it only returns two.

That's because we didn't have the correct icons assigned to each character. Should be fixed now

2024-01-08 21:08 UTC, martinacantaro submitted a review, later dismissed

2024-01-09 19:56 UTC, lotuuu requested changes

2024-01-09 19:56 UTC, lotuuu commented on client/Assets/Scripts/OpponentData.cs
> +                    new Unit { id = "101", level = 5, character = characters.Find(character => "otix" == character.name.ToLower()), slot = 0, selected = true },
This change doesn't accomplish anything since it's just a fallback value. Opponent units are being set in the LineupManager GetOpponents() method. This will very soon change in #73.

2024-01-09 20:39 UTC, lotuuu approved these changes

2024-01-10 15:41 UTC, merged