Add currencies and display in header
lambdaclass/champions_of_mirra pull request #88
Opened 2024-01-11 15:39 UTC by lotuuu

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-01-12 21:52 UTC, martinacantaro commented
Very good start! I tried it in play mode
- I received 15 gold for each victory in the campaign, 500 for finishing the level
- I earned 100 xp for finishing the level
- when I bought a rare champion, it charged me 30 gold
- when I bought an epic champion, it charged me 100 gold AND 100 experience.

Haven't looked at the code yet, @ncontinanza please take a look at it on Monday before we merge

2024-01-15 20:24 UTC, ncontinanza requested changes

2024-01-15 20:24 UTC, ncontinanza commented on client/Assets/Scripts/Campaign/Level.cs
> +    }
```suggestion
```

2024-01-15 20:24 UTC, ncontinanza commented on client/Assets/Scripts/Campaign/Level.cs
> +    }
This method seems to be unused

2024-01-15 22:05 UTC, lotuuu commented on client/Assets/HeaderManager.cs
> +        gold.text = user.GetCurrency("gold").ToString();
As we discussed, even though this makes our front-end less backend agnostic (since now we need to know which currencies will be coming from it if there ever are any), in the short term it's much better to develop this way as we don't get typos or anything. Overall I think it's fine to change this and eventually revert it later if we need to.

2024-01-15 22:05 UTC, lotuuu commented on client/Assets/Scripts/Campaign/Level.cs
> +    }
Solved!

2024-01-16 14:38 UTC, ncontinanza approved these changes

2024-01-16 14:45 UTC, ncontinanza approved these changes

2024-01-16 15:13 UTC, martinacantaro approved these changes

2024-01-16 15:13 UTC, merged