Update README.md
lambdaclass/champions_of_mirra pull request #91
Opened 2024-01-12 20:30 UTC by martinacantaro

Change the dotween link to their website for the download link in the unity asset store website. I think it's more secure to download things from the asset store

Closes #[issue]

## Motivation

Explain why not how.

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

2024-01-12 21:46 UTC, lotuuu requested changes

2024-01-12 21:46 UTC, lotuuu commented on README.md
> +  - Download [DOTween]([https://dotween.demigiant.com/](https://assetstore.unity.com/packages/tools/animation/dotween-hotween-v2-27676)), follow the standard setup instructions and save it in the `As
Link is broken! This should be 

`[DOTween](https://assetstore.unity.com/packages/tools/animation/dotween-hotween-v2-27676))`

Also make sure to add it back to the Unity Asset Store section then (basically reverting this change https://github.com/lambdaclass/champions_of_mirra/pull/77/commits/c369b3f615d3cae60dc4393d1fd3dda4ae7b7fab)

2024-03-25 22:00 UTC, AngieDutra approved these changes
Nice ✨

2024-03-26 13:42 UTC, lotuuu approved these changes

2024-03-26 13:43 UTC, merged